In [1]:
#Задаем период отчета
import datetime
from datetime import timedelta
DATE_START = datetime.datetime(2020, 5, 5) 
DATE_END = datetime.datetime(2020, 11, 20)

In [2]:
import pandas as pd
import gspread
sheet_id = '1Ycg7zTxds9DZnDvTrFcyNNKuTUxg6Yy6WF0a8Wc02WQ'
gc = gspread.service_account()

In [3]:
sh = gc.open_by_key(sheet_id)
worksheet = sh.worksheet('transactions')
df_transactions = pd.DataFrame(worksheet.get_all_records())

In [4]:
df_transactions

,transaction_id,created_at,m_real_amount,l_client_id
0,2c9f1527-8e7f-4fb1-8000-c747a2ab46c9,2020-09-30 07:15:14,31,8a805e60-6fd6-11e7-80fc-c412f533dba1
1,2c9f1527-8e7f-4fb1-8000-c747a2ab46c9,2020-09-30 07:15:14,87,8a805e60-6fd6-11e7-80fc-c412f533dba1
2,ab8cbcf7-3271-49a0-8001-6cf9816f63b8,2020-09-12 13:47:04,49231,dc0d0e52-629a-11ea-abf3-c412f533dba1
3,ab8cbcf7-3271-49a0-8001-6cf9816f63b8,2020-09-12 13:47:04,17305,dc0d0e52-629a-11ea-abf3-c412f533dba1
4,52f8ebcc-d82d-4be1-8004-72cfbe0dff24,2020-09-25 06:00:07,9022,e663b6a0-4a1a-11e8-a2c3-c412f533dba1
...,...,...,...,...
28995,39119f9c-d15b-46e6-bffa-1361257415cd,2020-07-21 21:02:34,0,b56326a0-d5a2-11e9-abbe-c412f533dba1
28996,74fa1409-2a93-4a3e-bffb-d2cd0c75f6a5,2020-01-23 03:45:41,0,1a32cb98-d5a2-11e9-abbe-c412f533dba1
28997,b5959542-894b-4eda-bffc-8ecaaed4f9e5,2020-09-03 06:45:51,0,55953b37-d5af-11e9-abbe-c412f533dba1
28998,c7cb1253-6e03-4531-bffe-81866395abce,2020-08-13 22:42:08,0,547f3c7b-d5a4-11e9-abbe-c412f533dba1
28999,c7cb1253-6e03-4531-bffe-81866395abce,2020-09-17 09:16:10,0,547f3c7b-d5a4-11e9-abbe-c412f533dba1

In [5]:
worksheet = sh.worksheet('clients')
df_clients = pd.DataFrame(worksheet.get_all_records())

In [6]:
df_clients

,client_id,created_at,l_manager_id
0,0001da7d-fcda-11ea-ac18-c412f533dba1,2020-09-22 17:46:23,9a87c608-52dc-11ea-abeb-c412f533dba1
1,000a8743-9ae1-11e7-8114-c412f533dba1,2017-09-16 00:00:00,ad52c7a8-a752-11e7-8115-c412f533dba1
2,000ae57e-2d48-11ea-abeb-c412f533dba1,2020-01-02 14:08:56,43756fa4-57a0-11e9-ab9a-c412f533dba1
3,00133cde-481c-11ea-abeb-c412f533dba1,2020-02-05 17:25:13,9a87c608-52dc-11ea-abeb-c412f533dba1
4,00148d3f-07e6-11e8-812a-c412f533dba1,2018-02-02 00:00:00,abed5496-ca88-11e9-abb8-c412f533dba1
...,...,...,...
75761,ffeed40c-3a7e-11e9-ab8e-c412f533dba1,2019-02-27 00:00:00,db06b8bc-bfb2-11e7-8116-c412f533dba1
75762,fff022a5-2c34-11e8-8131-c412f533dba1,2018-03-20 00:00:00,d12fe765-b444-11e9-abb3-c412f533dba1
75763,fff88086-11bb-11ea-abe7-c412f533dba1,2019-11-28 12:48:58,bf340611-034b-11eb-ac18-c412f533dba1
75764,fff9ba6e-de05-11e9-abc1-c412f533dba1,2019-09-23 17:27:42,43756fa4-57a0-11e9-ab9a-c412f533dba1
75765,fffd756f-d49a-11e9-abbe-c412f533dba1,2019-09-11 17:48:52,31298620-0355-11eb-ac18-c412f533dba1

In [7]:
worksheet = sh.worksheet('managers')
df_managers = pd.DataFrame(worksheet.get_all_records())

In [8]:
df_managers

                              manager_id    d_manager   d_club
0   1e9c5562-0cfc-11ea-abe1-c412f533dba1   manager #8  club #2
1   43756fa4-57a0-11e9-ab9a-c412f533dba1  manager #11  club #4
2   543888c4-fbb3-11e9-abdc-c412f533dba1  manager #12  club #3
3   5dd88f32-6501-11ea-abf3-c412f533dba1  manager #10  club #2
4   9a87c608-52dc-11ea-abeb-c412f533dba1   manager #9  club #3
5   abed5496-ca88-11e9-abb8-c412f533dba1   manager #5  club #4
6   ad52c7a8-a752-11e7-8115-c412f533dba1   manager #7  club #1
7   b55a233c-5df6-11ea-abf2-c412f533dba1   manager #2  club #4
8   b832aac3-fcda-11ea-ac18-c412f533dba1  manager #13  club #3
9   d12fe765-b444-11e9-abb3-c412f533dba1   manager #1  club #1
10  db06b8bc-bfb2-11e7-8116-c412f533dba1   manager #4  club #2
11  e463b03f-2d74-11eb-ac1f-c412f533dba1   manager #3  club #1
12  f44596c6-12cd-11eb-ac1c-c412f533dba1   manager #6  club #2

In [9]:
worksheet = sh.worksheet('leads')
df_leads = pd.DataFrame(worksheet.get_all_records())

In [10]:
df_leads

,lead_id,created_at,d_utm_medium,d_utm_source,l_manager_id,l_client_id
0,00678e71-0fb9-11eb-ac1a-c412f533dba1,2020-10-16 18:08:09,sms,viber,1e9c5562-0cfc-11ea-abe1-c412f533dba1,7264cf21-a31d-11e9-abb0-c412f533dba1
1,0078b05d-0f1f-11eb-ac1a-c412f533dba1,2020-10-15 23:45:40,cpc,instagram,d12fe765-b444-11e9-abb3-c412f533dba1,606c5b29-0f88-11eb-ac1a-c412f533dba1
2,007d1401-2af3-11eb-ac1f-c412f533dba1,2020-11-20 09:41:14,cpc,instagram,43756fa4-57a0-11e9-ab9a-c412f533dba1,1f389c6a-d5ab-11e9-abbe-c412f533dba1
3,0084e614-2fcc-11eb-ac1f-c412f533dba1,2020-11-26 13:44:40,,,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000
4,009b1616-145d-11eb-ac1d-c412f533dba1,2020-10-22 15:52:04,cpc,vk,5dd88f32-6501-11ea-abf3-c412f533dba1,ac2c0012-6fd5-11e7-80fc-c412f533dba1
...,...,...,...,...,...,...
3332,ffaa0815-16c4-11eb-ac1d-c412f533dba1,2020-10-25 17:21:33,,,5dd88f32-6501-11ea-abf3-c412f533dba1,ffaa0816-16c4-11eb-ac1d-c412f533dba1
3333,ffacb5af-194f-11eb-ac1d-c412f533dba1,2020-10-28 23:01:35,cpc,vk,ad52c7a8-a752-11e7-8115-c412f533dba1,377ea5e0-d089-11e9-abbd-c412f533dba1
3334,ffbd53f1-3150-11eb-ac1f-c412f533dba1,2020-11-28 12:09:13,cpc,google,5dd88f32-6501-11ea-abf3-c412f533dba1,6dd39f15-d5a3-11e9-abbe-c412f533dba1
3335,ffc0b363-2ae9-11eb-ac1f-c412f533dba1,2020-11-20 08:36:48,cpc,instagram,ad52c7a8-a752-11e7-8115-c412f533dba1,00000000-0000-0000-0000-000000000000
3336,ffcdebc8-15c2-11eb-ac1d-c412f533dba1,2020-10-24 10:34:43,utm_medium,utm_source,ad52c7a8-a752-11e7-8115-c412f533dba1,f3357d13-15c7-11eb-ac1d-c412f533dba1

In [11]:
df_leads['d_utm_source'].value_counts()

                                            1243
instagram                                    920
utm_source                                   379
viber                                        205
yandex                                       164
google                                       145
vk                                            98
sms                                           83
vkontakte                                     61
insta                                         19
ycard                                         15
ig                                             4
ycard#!/tproduct/225696739-1498486363994       1
Name: d_utm_source, dtype: int64

In [12]:
df_leads = df_leads.replace({'vk':'vkontakte','ig':'instagram','insta':'instagram','ycard#!/tproduct/225696739-1498486363994':'ycard','':'other' })
df_leads

,lead_id,created_at,d_utm_medium,d_utm_source,l_manager_id,l_client_id
0,00678e71-0fb9-11eb-ac1a-c412f533dba1,2020-10-16 18:08:09,sms,viber,1e9c5562-0cfc-11ea-abe1-c412f533dba1,7264cf21-a31d-11e9-abb0-c412f533dba1
1,0078b05d-0f1f-11eb-ac1a-c412f533dba1,2020-10-15 23:45:40,cpc,instagram,d12fe765-b444-11e9-abb3-c412f533dba1,606c5b29-0f88-11eb-ac1a-c412f533dba1
2,007d1401-2af3-11eb-ac1f-c412f533dba1,2020-11-20 09:41:14,cpc,instagram,43756fa4-57a0-11e9-ab9a-c412f533dba1,1f389c6a-d5ab-11e9-abbe-c412f533dba1
3,0084e614-2fcc-11eb-ac1f-c412f533dba1,2020-11-26 13:44:40,other,other,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000
4,009b1616-145d-11eb-ac1d-c412f533dba1,2020-10-22 15:52:04,cpc,vkontakte,5dd88f32-6501-11ea-abf3-c412f533dba1,ac2c0012-6fd5-11e7-80fc-c412f533dba1
...,...,...,...,...,...,...
3332,ffaa0815-16c4-11eb-ac1d-c412f533dba1,2020-10-25 17:21:33,other,other,5dd88f32-6501-11ea-abf3-c412f533dba1,ffaa0816-16c4-11eb-ac1d-c412f533dba1
3333,ffacb5af-194f-11eb-ac1d-c412f533dba1,2020-10-28 23:01:35,cpc,vkontakte,ad52c7a8-a752-11e7-8115-c412f533dba1,377ea5e0-d089-11e9-abbd-c412f533dba1
3334,ffbd53f1-3150-11eb-ac1f-c412f533dba1,2020-11-28 12:09:13,cpc,google,5dd88f32-6501-11ea-abf3-c412f533dba1,6dd39f15-d5a3-11e9-abbe-c412f533dba1
3335,ffc0b363-2ae9-11eb-ac1f-c412f533dba1,2020-11-20 08:36:48,cpc,instagram,ad52c7a8-a752-11e7-8115-c412f533dba1,00000000-0000-0000-0000-000000000000
3336,ffcdebc8-15c2-11eb-ac1d-c412f533dba1,2020-10-24 10:34:43,utm_medium,utm_source,ad52c7a8-a752-11e7-8115-c412f533dba1,f3357d13-15c7-11eb-ac1d-c412f533dba1

In [13]:
df_leads.dtypes

lead_id         object
created_at      object
d_utm_medium    object
d_utm_source    object
l_manager_id    object
l_client_id     object
dtype: object

In [14]:
df_leads.created_at = pd.to_datetime(df_leads.created_at, errors = 'coerce')
df_transactions.created_at = pd.to_datetime(df_transactions.created_at, errors = 'coerce') 
df_clients.created_at = pd.to_datetime(df_clients.created_at, errors = 'coerce')

In [15]:
#обрезаем датасеты по дням отчета
DATE_START = pd.to_datetime(DATE_START)
DATE_END = pd.to_datetime(DATE_END)

In [16]:
df_leads_select = df_leads[(DATE_START <= df_leads['created_at']) & (df_leads['created_at'] <= DATE_END)]

In [17]:
result = [] #итоговая таблица
for manager in df_managers['manager_id']:
    for source in df_leads_select['d_utm_source'].unique():
        leads = df_leads_select[(df_leads_select.d_utm_source == source) & (df_leads_select.l_manager_id == manager)] #количество заявок
        leads_noclient = 0 #количество мусорных заявок
        leads_new = 0  #количество новых заявок
        leads_tocustomer = 0  #количество покупателей
        leads_tocustomer_new = 0  #количество новых покупателей
        revenue = 0  #доход от покупок новых покупателей
        for client, day in zip(leads.l_client_id, leads.created_at):        
            if len(df_clients[(df_clients.client_id == client) & (df_clients.l_manager_id == manager)]) == 0:
                leads_noclient += 1  
            if (len(df_leads[(df_leads.l_client_id == client) & (df_leads.created_at < day)]) == 0) & (len(df_transactions[(df_transactions.l_client_id == client) & (df_transactions.created_at < day)]) == 0):
                leads_new += 1    
            day2=day + datetime.timedelta(days=7) 
            condition1 = ((day <= df_transactions.created_at) & (df_transactions.created_at <= day2)) #купил в течение недели
            condition2 = (df_transactions.l_client_id == client) #текущий клиент
            condition3 = ((df_transactions.created_at < day)) #не покупал раньше
            if len(df_transactions[condition1 & condition2] != 0):
                leads_tocustomer += 1
                if len(df_transactions[condition2 & condition3]) == 0:
                    leads_tocustomer_new += 1
                    transactions = df_transactions[condition1 & condition2] #вытаскиваем транзакции за неделю
                    revenue += transactions.m_real_amount.sum()
        result.append([manager, source, len(leads), leads_noclient, leads_new, leads_tocustomer, leads_tocustomer_new, revenue])

In [18]:
print(*result, sep = "\n")

['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'viber', 19, 6, 12, 3, 2, 66645]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'instagram', 74, 26, 52, 16, 11, 171287]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'vkontakte', 10, 8, 1, 0, 0, 0]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'sms', 5, 0, 4, 0, 0, 0]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'other', 58, 15, 44, 10, 9, 290257]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'google', 8, 4, 4, 2, 0, 0]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'utm_source', 47, 20, 36, 8, 7, 332558]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'yandex', 11, 2, 8, 4, 3, 99769]
['1e9c5562-0cfc-11ea-abe1-c412f533dba1', 'ycard', 3, 1, 3, 1, 1, 79395]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'viber', 16, 8, 11, 3, 2, 41658]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'instagram', 99, 30, 61, 16, 16, 319354]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'vkontakte', 21, 7, 14, 5, 4, 133885]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'sms', 2, 1, 2, 0, 0, 0]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'other', 99, 81, 12, 6, 4, 115666]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'google', 17, 6, 11, 3, 3, 39713]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'utm_source', 33, 9, 28, 5, 5, 259962]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'yandex', 16, 5, 11, 2, 2, 25540]
['43756fa4-57a0-11e9-ab9a-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'viber', 1, 1, 1, 1, 1, 51586]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'instagram', 10, 5, 5, 3, 1, 20666]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'vkontakte', 1, 1, 0, 0, 0, 0]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'sms', 1, 1, 1, 0, 0, 0]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'other', 19, 8, 15, 8, 8, 203713]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'google', 1, 0, 1, 0, 0, 0]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'utm_source', 5, 0, 5, 1, 1, 16294]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'yandex', 1, 0, 1, 0, 0, 0]
['543888c4-fbb3-11e9-abdc-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'viber', 7, 1, 2, 2, 2, 62931]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'instagram', 37, 11, 24, 9, 5, 54645]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'vkontakte', 15, 3, 10, 7, 7, 183605]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'sms', 7, 0, 5, 1, 1, 21510]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'other', 41, 7, 33, 9, 8, 287426]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'google', 10, 2, 4, 0, 0, 0]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'utm_source', 19, 9, 12, 5, 4, 176160]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'yandex', 9, 1, 8, 4, 3, 224051]
['5dd88f32-6501-11ea-abf3-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'viber', 28, 8, 20, 3, 2, 50399]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'instagram', 88, 20, 69, 9, 7, 249999]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'vkontakte', 11, 3, 6, 4, 4, 201970]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'sms', 1, 0, 1, 0, 0, 0]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'other', 62, 17, 32, 7, 7, 277847]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'google', 13, 5, 6, 1, 1, 40739]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'utm_source', 23, 10, 15, 2, 2, 91794]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'yandex', 26, 5, 20, 2, 1, 56094]
['9a87c608-52dc-11ea-abeb-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'viber', 23, 8, 19, 3, 3, 142500]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'instagram', 71, 21, 55, 7, 7, 53899]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'vkontakte', 9, 8, 4, 3, 3, 122654]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'sms', 1, 1, 1, 0, 0, 0]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'other', 88, 28, 48, 17, 15, 429488]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'google', 9, 3, 7, 1, 1, 483]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'utm_source', 23, 6, 21, 6, 6, 283907]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'yandex', 10, 2, 8, 2, 2, 66722]
['abed5496-ca88-11e9-abb8-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'viber', 9, 7, 7, 2, 1, 10030]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'instagram', 69, 28, 45, 6, 6, 48627]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'vkontakte', 6, 1, 5, 4, 4, 52417]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'sms', 0, 0, 0, 0, 0, 0]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'other', 52, 14, 31, 9, 8, 204538]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'google', 5, 1, 4, 0, 0, 0]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'utm_source', 14, 5, 11, 6, 6, 215014]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'yandex', 8, 1, 7, 0, 0, 0]
['ad52c7a8-a752-11e7-8115-c412f533dba1', 'ycard', 2, 1, 2, 1, 1, 22628]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'viber', 20, 10, 11, 2, 1, 32126]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'instagram', 62, 10, 41, 12, 10, 36955]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'vkontakte', 6, 0, 4, 2, 1, 17394]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'sms', 8, 3, 5, 0, 0, 0]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'other', 49, 22, 17, 6, 5, 131975]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'google', 5, 2, 3, 1, 1, 76873]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'utm_source', 19, 3, 15, 4, 3, 99515]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'yandex', 9, 3, 6, 3, 3, 194669]
['b55a233c-5df6-11ea-abf2-c412f533dba1', 'ycard', 1, 1, 1, 0, 0, 0]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'viber', 13, 9, 10, 1, 1, 61618]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'instagram', 99, 35, 70, 23, 19, 316246]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'vkontakte', 17, 3, 8, 4, 2, 99170]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'sms', 1, 0, 0, 0, 0, 0]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'other', 69, 15, 34, 13, 12, 268905]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'google', 11, 8, 6, 2, 2, 53558]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'utm_source', 28, 14, 14, 5, 4, 119653]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'yandex', 8, 3, 5, 3, 2, 8412]
['b832aac3-fcda-11ea-ac18-c412f533dba1', 'ycard', 1, 1, 1, 0, 0, 0]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'viber', 30, 14, 14, 7, 6, 186223]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'instagram', 143, 56, 93, 12, 10, 195661]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'vkontakte', 9, 1, 7, 3, 2, 88419]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'sms', 3, 1, 2, 0, 0, 0]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'other', 45, 16, 16, 8, 2, 34479]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'google', 17, 8, 10, 3, 3, 64811]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'utm_source', 36, 11, 26, 6, 5, 159590]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'yandex', 21, 9, 12, 3, 3, 130365]
['d12fe765-b444-11e9-abb3-c412f533dba1', 'ycard', 1, 0, 1, 0, 0, 0]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'viber', 20, 4, 16, 1, 1, 61851]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'instagram', 68, 22, 51, 17, 14, 232315]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'vkontakte', 11, 1, 7, 3, 3, 78803]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'sms', 9, 2, 5, 1, 1, 75151]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'other', 77, 10, 60, 7, 5, 263299]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'google', 8, 2, 5, 2, 2, 12047]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'utm_source', 46, 5, 40, 6, 6, 295713]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'yandex', 18, 3, 14, 3, 3, 142137]
['db06b8bc-bfb2-11e7-8116-c412f533dba1', 'ycard', 1, 1, 0, 1, 1, 3670]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'viber', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'instagram', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'vkontakte', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'sms', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'other', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'google', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'utm_source', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'yandex', 0, 0, 0, 0, 0, 0]
['e463b03f-2d74-11eb-ac1f-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'viber', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'instagram', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'vkontakte', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'sms', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'other', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'google', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'utm_source', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'yandex', 0, 0, 0, 0, 0, 0]
['f44596c6-12cd-11eb-ac1c-c412f533dba1', 'ycard', 0, 0, 0, 0, 0, 0]

In [19]:
df = pd.DataFrame(result, columns = ['manager','канал привлечения заявки','количество заявок','количество мусорных заявок','количество новых заявок','количество покупателей', 'количество новых покупателей', 'доход от покупок новых покупателей'])
df

,manager,канал привлечения заявки,количество заявок,количество мусорных заявок,количество новых заявок,количество покупателей,количество новых покупателей,доход от покупок новых покупателей
0,1e9c5562-0cfc-11ea-abe1-c412f533dba1,viber,19,6,12,3,2,66645
1,1e9c5562-0cfc-11ea-abe1-c412f533dba1,instagram,74,26,52,16,11,171287
2,1e9c5562-0cfc-11ea-abe1-c412f533dba1,vkontakte,10,8,1,0,0,0
3,1e9c5562-0cfc-11ea-abe1-c412f533dba1,sms,5,0,4,0,0,0
4,1e9c5562-0cfc-11ea-abe1-c412f533dba1,other,58,15,44,10,9,290257
...,...,...,...,...,...,...,...,...
112,f44596c6-12cd-11eb-ac1c-c412f533dba1,other,0,0,0,0,0,0
113,f44596c6-12cd-11eb-ac1c-c412f533dba1,google,0,0,0,0,0,0
114,f44596c6-12cd-11eb-ac1c-c412f533dba1,utm_source,0,0,0,0,0,0
115,f44596c6-12cd-11eb-ac1c-c412f533dba1,yandex,0,0,0,0,0,0
116,f44596c6-12cd-11eb-ac1c-c412f533dba1,ycard,0,0,0,0,0,0

In [20]:
df = df.merge(df_managers, left_on='manager', right_on='manager_id')
df = df.drop(['manager', 'manager_id'], axis=1)

In [21]:
cols = df.columns.tolist()
cols = cols[-2:] + cols[:-2]
df = df[cols]

In [22]:
#сохраняем в spreadsheet
spreadsheet_id = '1pdFPnZp9s3UXiX4iGBqghbRVxFPAsJCJd22h-aX4YDo'
gc = gspread.service_account()
wks = gc.open_by_key(spreadsheet_id)
worksheet = wks.get_worksheet(0)
worksheet.update([df.columns.values.tolist()] + df.values.tolist())

{'spreadsheetId': '1pdFPnZp9s3UXiX4iGBqghbRVxFPAsJCJd22h-aX4YDo',
 'updatedRange': "'Данные'!A1:I118",
 'updatedRows': 118,
 'updatedColumns': 9,
 'updatedCells': 1062}

In [23]:
import httplib2 
import apiclient.discovery
from oauth2client.service_account import ServiceAccountCredentials

CREDENTIALS_FILE = 'add'  #removed

credentials = ServiceAccountCredentials.from_json_keyfile_name(CREDENTIALS_FILE, ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive'])

httpAuth = credentials.authorize(httplib2.Http())
service = apiclient.discovery.build('sheets', 'v4', http = httpAuth)

In [24]:
sourceSheetId = 0

request_body = {

  "requests": [
    {
      "updateCells": {
        "rows": {
          "values": [
            {
              "pivotTable": {
                "source": {
                  "sheetId": sourceSheetId,
                  "startRowIndex": 0,
                  "startColumnIndex": 0,
                  "endRowIndex": 118,
                  "endColumnIndex": 9
                },
                "rows": [
                  {
                    "sourceColumnOffset": 2,
                    "showTotals": True,
                    "sortOrder": "ASCENDING"
                  },
                  {
                    "sourceColumnOffset": 1,
                    "showTotals": False,
                    "sortOrder": "ASCENDING",
                  },
                  {
                    "sourceColumnOffset": 0,
                    "showTotals": False,
                    "sortOrder": "ASCENDING",
                  }
                ],

                "values": [
                  {
                    "summarizeFunction": "SUM",
                    "name": "количество заявок",
                    "sourceColumnOffset": 3
                  },
                  {
                    "summarizeFunction": "SUM",
                    "name": "количество мусорных заявок",
                    "sourceColumnOffset": 4
                  },
                  {
                    "summarizeFunction": "SUM",
                    "name": "количество новых заявок",
                    "sourceColumnOffset": 5
                  },  
                  {
                    "summarizeFunction": "SUM",
                    "name": "количество покупателей",
                    "sourceColumnOffset": 6
                  }, 
                  {
                    "summarizeFunction": "SUM",
                    "name": "количество новых покупателей",
                    "sourceColumnOffset": 7
                  }, 
                  {
                    "summarizeFunction": "SUM",
                    "name": "доход от покупок новых покупателей",
                    "sourceColumnOffset": 8
                  }, 
                ],
                "valueLayout": "VERTICAL"
              }
            }
          ]
        },
        "start": {
          "sheetId": 533791918,
          "rowIndex": 1,
          "columnIndex": 0
        },
        "fields": "pivotTable"
      }
    }
  ]
}    
    
    

response = service.spreadsheets().batchUpdate(
    spreadsheetId=spreadsheet_id,
    body=request_body
).execute()

In [25]:
results = service.spreadsheets().values().batchUpdate(spreadsheetId = spreadsheet_id, body = {
    "valueInputOption": "USER_ENTERED",
    "data": [
        {"range": "Отчет!A1:C1",
         "majorDimension": "ROWS",     
         "values": [["Период отчета:", str(DATE_START.date()), str(DATE_END.date())]]},
    ]
}).execute()